# ************************************ Windwos ************************************
[database]
dbtype = "sqlite"
path = "sqlite3.db"
targets = ["D:\\"] # 指定监听的文件路径前缀, C盘数据读写频繁, 建议不要直接监听C的根目录
blacklist = [
    # ******************* 开发黑名单 ********************
    ".*build.*",
    ".*target.*",
    ".*[Cc]ache.*",     # 缓存文件夹
    ".*\\.git.*",       # git仓库
    ".*\\.vscode.*",    # VSCode项目配置信息
    ".*\\.idea.*",      # jetbrain项目配置信息
    ".*node_modules.*", # node_modules, node的package, 数量太多

    # ******************* 微信黑名单 ********************
    ".*WeChat Files\\\\.*\\\\Msg.*",                          # 微信的消息记录
    ".*WeChat Files\\\\.*\\\\config.*",                       # 微信的配置信息
    ".*WeChat Files\\\\.*\\\\FileStorage\\\\MsgAttach.*",     # 微信文件附属消息
    ".*WeChat Files\\\\.*\\\\FileStorage\\\\CustomEmotion.*", # 微信的表情

    # ******************* QQ黑名单 ********************
    ".*QQ files.*\\\\nt_qq.*\\\\nt_db.*",   # QQ本地数据库
    ".*QQ files.*\\\\nt_qq.*\\\\nt_temp.*", # QQ临时数据
    ".*QQ files.*\\\\nt_qq.*\\\\nt_data*",  # QQ数据


    # ******************* 自定义黑名单 ********************
    ".*file_elf.*", # 滤除工具本身

] # 黑名单列表，支持使用正则表达式
hotdirnum = 100
log_level = "info" # 日志级别
# 注意, windows中使用\\表示分隔符, \需要\\转义, 因此正则表达式中的分隔符为\\\\


# ************************************ Linux or MacOS ************************************
# [database]
# dbtype = "sqlite" # 数据库类型
# path = "/home/toni/proj/file_elf/sqlite3.db" # 数据库文件路径
# targets = ["/home/toni/Course", "/home/toni/proj"] # 监控目录
# blacklist = [".*/build/.*", ".*/target/.*", ".*file_elf.*"] # 黑名单列表，支持使用正则表达式
# hotdirnum = 100
# log_level = "info" # 日志级别
